name: Typecheck and cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Set up Cachix
        uses: cachix/cachix-action@v10
        with:
          name: compiler9000
          extraPullNames: lean4
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}' # optional

      - name: Build the Compiler9000
        run: nix build --no-link

      - name: Build the VSCode development environment
        run: nix build ".#vscode-dev"
